### ISSUE TITLE
Publish from `lerna` monorepo fails (Cannot read property 'includes' of undefined when publishing)

### ISSUE THREAD

**Issue by kevinpschaaf** [changesets/action#112]
When attempting to publish from our `lerna` monorepo (https://github.com/lit/lit), we've been getting the following error from the publishing step:

```
2021-10-07T23:18:05.0477899Z 🦋  warn @lit-labs/motion is not being published because version 1.0.1 is already published on npm
2021-10-07T23:18:05.0479505Z 🦋  warn @lit-labs/react is not being published because version 1.0.1 is already published on npm
2021-10-07T23:18:05.0480890Z 🦋  warn @lit-labs/scoped-registry-mixin is not being published because version 1.0.0 is already published on npm
2021-10-07T23:18:05.0482246Z 🦋  warn @lit-labs/ssr is not being published because version 1.0.0 is already published on npm
2021-10-07T23:18:05.0483505Z 🦋  warn @lit-labs/ssr-client is not being published because version 1.0.0 is already published on npm
2021-10-07T23:18:05.0484742Z 🦋  warn @lit-labs/task is not being published because version 1.0.0 is already published on npm
2021-10-07T23:18:05.0485907Z 🦋  info lit is being published because our local version (2.0.1) has not been published on npm
2021-10-07T23:18:05.0487094Z 🦋  warn lit-element is not being published because version 3.0.1 is already published on npm
2021-10-07T23:18:05.0488279Z 🦋  warn lit-html is not being published because version 2.0.1 is already published on npm
2021-10-07T23:18:05.0489471Z 🦋  warn @lit/localize is not being published because version 0.11.0 is already published on npm
2021-10-07T23:18:05.0490707Z 🦋  warn @lit/localize-tools is not being published because version 0.4.0 is already published on npm
2021-10-07T23:18:05.0492155Z 🦋  warn @lit/reactive-element is not being published because version 1.0.1 is already published on npm
2021-10-07T23:18:05.0493426Z 🦋  warn @lit/ts-transformers is not being published because version 1.0.2 is already published on npm
2021-10-07T23:18:05.0502215Z 🦋  info Publishing "lit" at "2.0.1"
2021-10-07T23:18:06.7195484Z 🦋  success packages published successfully:
2021-10-07T23:18:06.7196962Z 🦋  lit@2.0.1
2021-10-07T23:18:06.7197852Z 🦋  Creating git tag...
2021-10-07T23:18:06.7198758Z 🦋  New tag:  lit@2.0.1
2021-10-07T23:18:06.7491906Z [command]/usr/bin/git push origin --tags
2021-10-07T23:18:07.6024711Z To https://github.com/lit/lit
2021-10-07T23:18:07.6026313Z  * [new tag]           lit@2.0.1 -> lit@2.0.1
2021-10-07T23:18:07.6861499Z TypeError: Cannot read property 'includes' of undefined
2021-10-07T23:18:07.6862550Z     at f (/home/runner/work/_actions/changesets/action/master/dist/index.js:906:1660)
2021-10-07T23:18:07.6864403Z     at async Object.w [as runPublish] (/home/runner/work/_actions/changesets/action/master/dist/index.js:906:2582)
2021-10-07T23:18:07.6865487Z     at async /home/runner/work/_actions/changesets/action/master/dist/index.js:908:1443
2021-10-07T23:18:07.6873666Z ##[error]Cannot read property 'includes' of undefined
2021-10-07T23:18:07.7025596Z ##[debug]Node Action run completed with exit code 1
2021-10-07T23:18:07.7034160Z ##[debug]Finishing: Create Release Pull Request or Publish to npm
```

The correct package gets npm published and git tagged, but it looks like in the step that creates the github release fails with `TypeError: Cannot read property 'includes' of undefined` on L40 in the code below:

https://github.com/changesets/action/blob/c2918239208f2162b9d27a87f491375c51592434/src/run.ts#L36-L42

It looks like the root cause is that the version of `@manypkg/get-packages` used fails to classify our monorepo as a `lerna` type and tries to push a release for our root monorepo package (which has no version, causing the code above to fail).

Running `1.0.1` of `@manypkg/get-packages` in our monorepo returns `root`:
```
> (async () => console.log((await require('@manypkg/get-packages').getPackages(process.cwd())).tool))()
Promise { <pending> }
> root
```

Running `1.1.1` of `@manypkg/get-packages` correctly detects `lerna`, so I suspect just bumping that dependency should fix our issue:
```
> (async () => console.log((await require('@manypkg/get-packages').getPackages(process.cwd())).tool))()
Promise { <pending> }
> lerna
```

**Comment by kevinpschaaf** [comment]
Updated `@manypkg/get-packages` to `1.1.1` in https://github.com/changesets/action/pull/113.
