### ISSUE TITLE
404 Not Found when creating GitHub Release

### ISSUE THREAD

**Issue by erikhofer** [changesets/action#224]
When I merge the PR I get the following error:

```
🦋  info Publishing "@ehtest/core" at "0.1.0"
🦋  success packages published successfully:
🦋  @ehtest/core@0.1.0
🦋  Creating git tag...
🦋  New tag:  @ehtest/core@0.1.0
/usr/bin/git push origin --tags
To https://github.com/scope42/turborepo-test
 * [new tag]         @ehtest/core@0.1.0 -> @ehtest/core@0.1.0
Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
    at o.get (/home/runner/work/_actions/changesets/action/v1/dist/index.js:716:444)
    at b (/home/runner/work/_actions/changesets/action/v1/dist/index.js:918:1723)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
o [HttpError]: Not Found
    at /home/runner/work/_actions/changesets/action/v1/dist/index.js:718:926
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async b (/home/runner/work/_actions/changesets/action/v1/dist/index.js:918:1569)
Error: Not Found
    at async Promise.all (index 0)
    at async Object.m [as runPublish] (/home/runner/work/_actions/changesets/action/v1/dist/index.js:918:2315)
    at async /home/runner/work/_actions/changesets/action/v1/dist/index.js:920:2012 {
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Fri, 14 Oct 2022 14:09:14 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-accepted-oauth-scopes': 'repo',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '0480:31DA:43DF3E:8AD625:63496D8A',
    'x-oauth-scopes': 'repo',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4998',
    'x-ratelimit-reset': '1665759850',
    'x-ratelimit-resource': 'core',
    'x-ratelimit-used': '2',
    'x-xss-protection': '0'
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/scope42/turborepo-test/releases',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/3.1.0 <environment undetectable>',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"name":"@ehtest/core@0.1.0","tag_name":"@ehtest/core@0.1.0","body":"### Minor Changes\\n\\n-   d4b516b: Make buttons cooler\\n","prerelease":false}',
    request: { agent: [Agent], hook: [Function: bound bound r] }
  },
  documentation_url: 'https://docs.github.com/rest/reference/repos#create-a-release'
}
```

Full log: https://github.com/scope42/turborepo-test/actions/runs/3250779482/jobs/5334909650

Workflow: https://github.com/scope42/turborepo-test/blob/9583767c7051179cba3091cff4774bbe7f4e854a/.github/workflows/release.yml

**Comment by erikhofer** [comment]
I solved this by adding the user the GitHub token was created for as a colaborator with write access. Interestingly enough, everything else including the creation of tags works without this.
