### ISSUE TITLE
Create GitHub tag/release with custom publishing

### ISSUE THREAD

**Issue by mholta** [changesets/action#269]
## Problem
We are using `changesets/action@v1` for versioning and publishing of a non-npm application (one "root" application, no packages). In our workflow we have implemented custom publishing as referred to (https://github.com/changesets/action#custom-publishing). This works as expected, apart from GitHub releases and git tags not being created. In a (separate) monorepo publishing to NPM, this is working as expected.

According to https://github.com/changesets/changesets/blob/main/docs/versioning-apps.md, it seems like this should be possible. We have tested that it works with `changeset/cli`.

As far as I can tell, after some investigation, `createRelease` is not called if `publish:` is not specified in the workflow. 

## Current workaround
After looking into the `runPublish` method, we found that putting `publish: yarn dummy-publish` in the workflow and `"dummy-release": "echo \"New tag:" && exit 0"` under scripts in `package.json`. This satisfies the condition.

https://github.com/changesets/action/blob/595655c3eae7136ff5ba18200406898904362926/src/run.ts#L133-L138

**Comment by Andarist** [comment]
> After looking into the runPublish method, we found that putting publish: yarn dummy-publish in the workflow and "dummy-release": "echo \"New tag:" && exit 0" under scripts in package.json. This satisfies the condition.

This is basically what I was also doing. I think that nowadays you should be able to make private packages taggable and that should automatically resolve the issue - I agree that it's not exactly obvious but perhaps it's just a documentation issue. This requirement is vaguely mentioned [here](https://github.com/changesets/changesets/blob/5c53bff0efeb5bbd72976b79aefe9d5805038ebd/docs/versioning-apps.md)

**Comment by mholta** [comment]
I see! So having a "dummy" publish script satisfying the `/New tag:/` regex is the best solution for now? Would it be worth mentioning in [versioning-apps.md](https://github.com/changesets/changesets/blob/main/docs/versioning-apps.md)? It took quite some time before I realised why [this PR](https://github.com/changesets/changesets/pull/662) didn't fix it.

> Note: Changesets only versions NPM package.json files, you can trigger releases for other package formats by creating workflows which trigger on tags/releases being created by changesets.

**Comment by Andarist** [comment]
> I see! So having a "dummy" publish script that satisfies the /New tag:/ regex is the best solution for now?

I'm not 100% sure but I think that with this `privatePackages: { version: true, tag: true }` your private package should get tagged and that in turn should output this `New tag:` into the stdout and thus the `changesets/action` should create a GitHub release for this. The main q is - how exactly you will kick off the actual publication of whatever you are publishing there? I usually do smth like `"release": "changeset publish && node ./handle-custom-publishing.js"`

> Would it be worth mentioning in [versioning-apps.md](https://github.com/changesets/changesets/blob/main/docs/versioning-apps.md)? It took quite some time before I realised why https://github.com/changesets/changesets/pull/662 didn't fix it.

I'm definitely open for docs PRs 😉

**Comment by mholta** [comment]
After some investigation and testing we found that including `changeset tag` in the action release script suffice.

**Comment by mholta** [comment]
Have you veen able to look into the PR @Andarist? I'll be more than happy to make changes or discuss the implementation.

**Comment by AlexandrosMelissas** [comment]
@mholta have you encountered this error yet when you merge changeset bot's pr for release?

```
setting git user
/usr/bin/git config user.name "github-actions[bot]"
/usr/bin/git config user.email "github-actions[bot]@users.noreply.github.com"
setting GitHub credentials
No changesets found, attempting to publish any unpublished packages to npm
No user .npmrc file found, creating one
/home/runner/setup-pnpm/node_modules/.bin/pnpm changeset tag
🦋  New tag:  api@0.9.1
🦋  Skipping tag (already exists):  panel@1.1.0
🦋  Skipping tag (already exists):  @house-manager/tsconfig@0.1.0
🦋  Skipping tag (already exists):  @house-manager/types@0.2.0
🦋  Skipping tag (already exists):  @house-manager/validation@0.1.0
/usr/bin/git push origin --tags
To https://github.com/AlexandrosMelissas/house-manager-mono
 ! [rejected]        api@0.9.1 -> api@0.9.1 (already exists)
error: failed to push some refs to 'https://github.com/AlexandrosMelissas/house-manager-mono'
Error: The process '/usr/bin/git' failed with exit code 1
    at m._setResult (/home/runner/work/_actions/changesets/action/v1/dist/index.js:136:7258)
    at m.CheckComplete (/home/runner/work/_actions/changesets/action/v1/dist/index.js:136:6686)
hint: Updates were rejected because the tag already exists in the remote.
    at ChildProcess.<anonymous> (/home/runner/work/_actions/changesets/action/v1/dist/index.js:136:5723)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
Error: The process '/usr/bin/git' failed with exit code 1
```

**Comment by psirenny** [comment]
@Andarist I've found that configuring Changesets with `privatePackages: { version: true, tag: true }` works in a Monorepo setup but not in a single-package repo because the root package isn't tagged.
