### ISSUE TITLE
Changeset publish is failing

### ISSUE THREAD

**Issue by MercerK** [changesets/action#281]
For some reason, the action doesn't seem to be publishing and I'm not sure why.

* Changeset opens Version Package
* I merge Version Package (we have squash & delete branch enabled)
* Checks run on main and ends up failing.

I attached the log below. I'm not sure how to fix it. It doesn't seem to be even running `yarn release`, which is `changeset publish`.

<details>
<summary>Log</summary>

```
2023-04-10T02:22:21.3187873Z ##[group]Run changesets/action@v1
2023-04-10T02:22:21.3188147Z with:
2023-04-10T02:22:21.3188390Z   publish: yarn release
2023-04-10T02:22:21.3188656Z   setupGitUser: true
2023-04-10T02:22:21.3188933Z   createGithubReleases: true
2023-04-10T02:22:21.3189197Z env:
2023-04-10T02:22:21.3189735Z   GITHUB_TOKEN: ***
2023-04-10T02:22:21.3190097Z   NPM_TOKEN: ***
2023-04-10T02:22:21.3190342Z ##[endgroup]
2023-04-10T02:22:21.4811920Z setting git user
2023-04-10T02:22:21.4868017Z [command]/usr/bin/git config user.name "github-actions[bot]"
2023-04-10T02:22:21.4972829Z [command]/usr/bin/git config user.email "github-actions[bot]@users.noreply.github.com"
2023-04-10T02:22:21.5010045Z setting GitHub credentials
2023-04-10T02:22:21.5253703Z [command]/usr/bin/git checkout changeset-release/main
2023-04-10T02:22:21.5342835Z error: pathspec 'changeset-release/main' did not match any file(s) known to git
2023-04-10T02:22:21.5367800Z [command]/usr/bin/git checkout -b changeset-release/main
2023-04-10T02:22:21.5418730Z Switched to a new branch 'changeset-release/main'
2023-04-10T02:22:21.5442967Z [command]/usr/bin/git reset --hard a2a6bdca71dc9d4f76bef06a1edf97b8cc6cf10c
2023-04-10T02:22:21.6591324Z HEAD is now at a2a6bdc Version Packages
2023-04-10T02:22:21.6779620Z [command]/opt/hostedtoolcache/node/16.20.0/x64/bin/node /home/runner/work/YamJS/YamJS/node_modules/@changesets/cli/bin.js version
2023-04-10T02:22:24.0494037Z 🦋  All files have been updated. Review them and commit at your leisure
2023-04-10T02:22:24.1565756Z [command]/usr/bin/git status --porcelain
2023-04-10T02:22:24.2387033Z [command]/usr/bin/git push origin HEAD:changeset-release/main --force
2023-04-10T02:22:25.0881278Z remote: 
2023-04-10T02:22:25.0882781Z remote: Create a pull request for 'changeset-release/main' on GitHub by visiting:        
2023-04-10T02:22:25.0884141Z remote:      https://github.com/Yam-JS/YamJS/pull/new/changeset-release/main        
2023-04-10T02:22:25.0884793Z remote: 
2023-04-10T02:22:25.0901345Z To https://github.com/Yam-JS/YamJS
2023-04-10T02:22:25.0902235Z  * [new branch]      HEAD -> changeset-release/main
2023-04-10T02:22:25.0960037Z {
2023-04-10T02:22:25.0960540Z   "total_count": 0,
2023-04-10T02:22:25.0961001Z   "incomplete_results": false,
2023-04-10T02:22:25.1004267Z   "items": []
2023-04-10T02:22:25.1004518Z }
2023-04-10T02:22:25.1004796Z creating pull request
2023-04-10T02:22:25.5121096Z a [HttpError]: Validation Failed: {"resource":"PullRequest","code":"custom","message":"No commits between main and changeset-release/main"}
2023-04-10T02:22:25.5121864Z     at /home/runner/work/_actions/changesets/action/v1/dist/index.js:192:1285
2023-04-10T02:22:25.5122427Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-04-10T02:22:25.5123021Z     at async Object.w [as runVersion] (/home/runner/work/_actions/changesets/action/v1/dist/index.js:970:5099)
2023-04-10T02:22:25.5123575Z     at async /home/runner/work/_actions/changesets/action/v1/dist/index.js:972:2406 {
2023-04-10T02:22:25.5123927Z   status: 422,
2023-04-10T02:22:25.5124173Z   response: {
2023-04-10T02:22:25.5124659Z     url: 'https://api.github.com/repos/Yam-JS/YamJS/pulls',
2023-04-10T02:22:25.5124990Z     status: 422,
2023-04-10T02:22:25.5125218Z     headers: {
2023-04-10T02:22:25.5125920Z       'access-control-allow-origin': '*',
2023-04-10T02:22:25.5127435Z       'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
2023-04-10T02:22:25.5128794Z       connection: 'close',
2023-04-10T02:22:25.5129173Z       'content-length': '237',
2023-04-10T02:22:25.5129622Z       'content-security-policy': "default-src 'none'",
2023-04-10T02:22:25.5130139Z       'content-type': 'application/json; charset=utf-8',
2023-04-10T02:22:25.5130853Z       date: 'Mon, 10 Apr 2023 02:22:25 GMT',
2023-04-10T02:22:25.5131482Z       'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
2023-04-10T02:22:25.5131989Z       server: 'GitHub.com',
2023-04-10T02:22:25.5132549Z       'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
2023-04-10T02:22:25.5133114Z       vary: 'Accept-Encoding, Accept, X-Requested-With',
2023-04-10T02:22:25.5133583Z       'x-content-type-options': 'nosniff',
2023-04-10T02:22:25.5133970Z       'x-frame-options': 'deny',
2023-04-10T02:22:25.5134437Z       'x-github-api-version-selected': '2022-11-28',
2023-04-10T02:22:25.5134936Z       'x-github-media-type': 'github.v3; format=json',
2023-04-10T02:22:25.5135478Z       'x-github-request-id': 'D001:35A0:7081890:743E944:643372E1',
2023-04-10T02:22:25.5135888Z       'x-ratelimit-limit': '1000',
2023-04-10T02:22:25.5136288Z       'x-ratelimit-remaining': '989',
2023-04-10T02:22:25.5136700Z       'x-ratelimit-reset': '1681093752',
2023-04-10T02:22:25.5137106Z       'x-ratelimit-resource': 'core',
2023-04-10T02:22:25.5137493Z       'x-ratelimit-used': '11',
2023-04-10T02:22:25.5137824Z       'x-xss-protection': '0'
2023-04-10T02:22:25.5138080Z     },
2023-04-10T02:22:25.5138298Z     data: {
2023-04-10T02:22:25.5138629Z       message: 'Validation Failed',
2023-04-10T02:22:25.5138908Z       errors: [Array],
2023-04-10T02:22:25.5139519Z       documentation_url: 'https://docs.github.com/rest/reference/pulls#create-a-pull-request'
2023-04-10T02:22:25.5139903Z     }
2023-04-10T02:22:25.5140109Z   },
2023-04-10T02:22:25.5140501Z   request: {
2023-04-10T02:22:25.5140799Z     method: 'POST',
2023-04-10T02:22:25.5141268Z     url: 'https://api.github.com/repos/Yam-JS/YamJS/pulls',
2023-04-10T02:22:25.5141605Z     headers: {
2023-04-10T02:22:25.5141999Z       accept: 'application/vnd.github.v3+json',
2023-04-10T02:22:25.5142544Z       'user-agent': 'octokit-core.js/3.6.0 Node.js/16.16.0 (linux; x64)',
2023-04-10T02:22:25.5143009Z       authorization: 'token [REDACTED]',
2023-04-10T02:22:25.5143490Z       'content-type': 'application/json; charset=utf-8'
2023-04-10T02:22:25.5143779Z     },
2023-04-10T02:22:25.5145399Z     body: `{"base":"main","head":"changeset-release/main","title":"Version Packages","body":"This PR was opened by the [Changesets release](https://github.com/changesets/action) GitHub action. When you're ready to do a release, you can merge this and the packages will be published to npm automatically. If you're not ready to do a release yet, that's fine, whenever you add more changesets to main, this PR will be updated.\\n\\n\\n# Releases"}`,
2023-04-10T02:22:25.5146356Z     request: { agent: [Agent], hook: [Function: bound bound r] }
2023-04-10T02:22:25.5146666Z   }
2023-04-10T02:22:25.5146888Z }
2023-04-10T02:22:25.5184146Z ##[error]Validation Failed: {"resource":"PullRequest","code":"custom","message":"No commits between main and changeset-release/main"}
2023-04-10T02:22:25.5300007Z Post job cleanup.
```
</details>

**Comment by MercerK** [comment]
It turns out:

I had bad changesets (a changeset that exists for a project that no longer needed changesets) merged within the codebase and didn't realize it. 

Maybe there can be some error handling or validation of detecting bad changesets somewhere in the process?

**Comment by marlonmarcello** [comment]
@MercerK I am having the same issue but can't seem to figure out the solution from your comment, any more info you can share that helped you debug this?

**Comment by bluwy** [comment]
It's a bit hard to figure out what the "bad changesets" setup look like for us to add the error handling, can you elaborate on that?

The action will only publish when there's no changeset in `main`, so is the issue that somehow after merging the "Version packages" PR there's still a dangling changeset in `main` that's blocking the publish?

**Comment by bluwy** [comment]
I'll close this as it's hard to tell how to replicate this case, and it has also been opened for some time. If someone can repro this, feel free to open a new issue and we can look into it again.
