### ISSUE TITLE
Action fails when NPM fetch fails

### ISSUE THREAD

**Issue by aulneau** [changesets/action#63]
When running the action within github, I get this error:

```bash
🦋  info npm info @stacks/ui
🦋  info npm info @stacks/ui-core
🦋  info npm info @stacks/ui-theme
🦋  info npm info @stacks/ui-utils
error parsing json: 
🦋  error SyntaxError: Unexpected end of JSON input
🦋  error     at JSON.parse (<anonymous>)
🦋  error     at jsonParse (/home/runner/work/ui/ui/node_modules/@changesets/cli/dist/cli.cjs.dev.js:557:17)
🦋  error     at /home/runner/work/ui/ui/node_modules/@changesets/cli/dist/cli.cjs.dev.js:628:12
🦋  error     at processTicksAndRejections (node:internal/process/task_queues:93:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: The process '/usr/bin/yarn' failed with exit code 1
Error: The process '/usr/bin/yarn' failed with exit code 1
```

which is revealed to be this error when testing locally:

```bash
error an error occurred while publishing @stacks/ui-core: E402 402 Payment Required - PUT https://registry.npmjs.org/@stacks%2fui-core - You must sign up for private packages 
```

I'm not actually sure why it fails, because publishing that package by itself works fine. 

It would be great if this error could be exposed more clearly from within the github actions UI.

Thanks for your work on this!

**Comment by ianpogi5** [comment]
Hi I'm new to changesets and also having a similar issue. 

As per instruction in kdcio/api-gw-resp#12, I merged it so it can auto publish to npm. Unfortunately it did not and got some error about the package not found in npm.

You can see the error here -> [https://github.com/kdcio/api-gw-resp/runs/2009534030?check_suite_focus=true#step:9:23](https://github.com/kdcio/api-gw-resp/runs/2009534030?check_suite_focus=true#step:9:23)

If I try to run `changeset publish` on my machine, I get the exact error message as @aulneau above.

I also tried publishing using my [original publish GA](https://github.com/kdcio/api-gw-resp/blob/master/.github/workflows/npmpublish.yml) and [it worked fine](https://github.com/kdcio/api-gw-resp/actions/runs/612651581).

Am I missing a step?

**Comment by Andarist** [comment]
@ianpogi5 this is just a little bit of information and is not sufficient for us to debug this. In general, most issues related to the CI are rather hard for us to debug - it would be highly appreciated if you could try to dig into this.

**Comment by ianpogi5** [comment]
> @ianpogi5 this is just a little bit of information and is not sufficient for us to debug this. In general, most issues related to the CI are rather hard for us to debug - it would be highly appreciated if you could try to dig into this.

Oh wow I thought I've provided too much information. My repo is open source and you can look at all the files and changes. 

Can you be more specific on what information you need?

**Comment by ianpogi5** [comment]
@Andarist I tried to deploy again and [same thing happened](https://github.com/kdcio/api-gw-resp/runs/2035049842?check_suite_focus=true#step:6:21). 

I did a bit of digging and it seems npm throws this error on scoped packages not being public. 

I was able to fix the issue by changing the access setting in `.changeset/config.json`.
https://github.com/kdcio/api-gw-resp/blob/ac8ba5a64d3fc8a3fce9a05992e5c128ef39d979/.changeset/config.json#L6

@aulneau hopefully this also solves your issue.

**Comment by ianpogi5** [comment]
I've created pull request #74 to remind about the public setting.

**Comment by alex-grover** [comment]
this bit me as well, it would be great to get the linked PR merged! it's not obvious from the docs here or from the getting started docs in https://github.com/changesets/changesets that the default is private.

**Comment by bluwy** [comment]
We now have docs about it here: https://changesets.dev/guide/versioning-and-publishing#publishing-for-the-first-time

Let's keep it in the official docs since this can happen for manual CLI calls as well, not only in actions.
